# Generated by Django 2.1.2 on 2018-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willno', models.CharField(max_length=255)),
                ('datesigned', models.DateTimeField()),
                ('timesubmit', models.DateTimeField()),
            ],
        ),
    ]
